name: Server Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'server/**'
      - '.github/workflows/server-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20, 22]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'server/package-lock.json'
        
    - name: Install dependencies
      working-directory: ./server
      run: npm ci
      
    - name: Run linting
      working-directory: ./server
      run: npm run lint || echo "Linting failed, but continuing..."
      
    - name: Run tests
      working-directory: ./server
      run: npm test
      
    - name: Test specific route
      working-directory: ./server
      run: npm test -- tests/unit/testRoute.test.js
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-node-${{ matrix.node-version }}
        path: server/coverage/
        retention-days: 7
